### PR TITLE
doc: fix wrong instructions; clean up links

### PR DESCRIPTION
**Pull request by jorgebucaran**
- Fix wrong instructions
- Clean up links

cc @FabioAntunes

### CODE REVIEW

**Comment by jorgebucaran** [comment]
@FabioAntunes

**Comment by jorgebucaran** [comment]
@FabioAntunes Ping?

**Comment by FabioAntunes** [comment]
Nop all good. Somehow I missed the email notification. Sorry about that.

**Comment by jorgebucaran** [comment]
🎉

**Comment by jorgebucaran** [comment]
@FabioAntunes Sorry for not creating a new issue, but I'd wanted to ask: is there any reason why you have two arbitrary .fish files in the top-level of the project and also a functions/ directory? Why the inconsistency?

**Comment by FabioAntunes** [comment]
Nothing special, the functions folder was added later with a subset of functions to be used by the user and the ones on the top level are kind of `private` functions for internal use. I will move all the functions to the functions folder since the separation doesn't make any sense at all.

**Comment by jorgebucaran** [comment]
Sounds good! 👍

**Comment by FabioAntunes** [comment]
@jorgebucaran done, thanks for noticing that.

**Pull request merged**
