### PR TITLE
Use Fisher 4.x

### PR DESCRIPTION
**Pull request by jorgebucaran**
The latest Fisher is no longer compatible with OMF.

### CODE REVIEW

**Comment by jorgebucaran** [comment]
@FabioAntunes Ready to merge here?

**Comment by FabioAntunes** [comment]
I'm not sure why the fact that the latest fisher not being compatible with OMF, makes my plugin not compatible as well?

this is still valid and has nothing to do with fisher:

```
omf install https://github.com/fabioantunes/fish-nvm	
omf install https://github.com/edc/bass
```

**Comment by jorgebucaran** [comment]
You're probably right, but double-check:

- OMF-specific `init.fish` and `uninstall.fish` files are no longer supported
- OMF doesn't support `conf.d` snippets

If you're not planning to use any of that ever, then you're probably right!

Now, it's ultimately up to you, but I feel that leading newcomers to OMF isn't a great idea. The project is [completely inactive](https://github.com/oh-my-fish/oh-my-fish/pulse). Long-standing [issues remain open](https://github.com/oh-my-fish/oh-my-fish/issues) even [after years](https://github.com/oh-my-fish/oh-my-fish/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-asc). Don't agree? No worries! I'm just proposing we don't send people to OMF.

**Comment by FabioAntunes** [comment]
I'm not sending people to anywhere, just providing installation guidelines. Just as any vim plugin will have installation guidelines for a bunch of plugin managers.

**Comment by FabioAntunes** [comment]
I have removed the fishfile and updated fisher installation guidelines from `add` to `install`.

Thanks for your help anyway

**Comment by jorgebucaran** [comment]
I totally understand your position. Thanks!

**Pull request closed without merging**
